### ISSUE TITLE
Document linkage requirements

### ISSUE THREAD

**Issue by sarum9in** [apolukhin/Boost.DLL#10]
Building a project that uses boost.dll under Linux results in: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
This can be fixed with `-ldl`.
I didn't try to do it under Windows, but I assume that other library may be required on non-Linux platforms.
By now I could only find linkage requirements in `test/Jamfile.v2`:
```
   # linux
      <target-os>linux:<linkflags>"-ldl" <target-os>linux:<cxxflags>"-fvisibility=hidden"
      <toolset>gcc:<cxxflags>"-Wall -Wextra -pedantic -Wno-long-long"

   # others
      <library>/boost/filesystem//boost_filesystem
      <library>/boost/system//boost_system
      <threading>multi
    ;   
```
But this is not obvious and not easy to read. Having it in official tutorial would be awesome.
Thanks.

**Comment by apolukhin** [comment]
Added note to the "Getting Started" section of the documentation.
