### ISSUE TITLE
Handling duplicate dependencies

### ISSUE THREAD

**Issue by axefrog** [apolukhin/Boost.DLL#12]
I'm learning how to use Boost.DLL at the moment (I haven't used shared libraries in my C++ code before now). I was wondering about the possible issues regarding (and ways to deal with) a plugin's own dependencies when there are multiple plugins that are unaware of each other but where each uses the same shared library. My directory structure will look something like this:

```
/bin/[main application files]
/bin/plugins/[plugin directories]
/bin/plugins/foo-plugin/plugin.dll
/bin/plugins/foo-plugin/[other files used by foo plugin.dll]
```

If I have two plugins, let's say "foo" and "bar", and both want to use the nanomsg library, which has a dll shared library, then each would end up with a copy of that dll in their respective plugin directories.

How would I deal with conflicts between the two? What's the common approach?

**Comment by apolukhin** [comment]
Actually, the behaviour may be different on different platforms. Linux may not load the the nanomsg library twice https://sourceware.org/ml/libc-help/2014-08/msg00038.html. Not sure about Windows but probably it will load two nanomsg shared libraries and each plugin will use it's own version.

It's better to avoid such cases by either
    * creating a /bin/plugins/common/ folder for nanomsg like libraries => one instance will be loaded
or
    * statically linking in the nanomsg and loading plugins with load_mode::rtld_deepbind http://apolukhin.github.io/Boost.DLL/boost/dll/load_mode/type.html => each plugin will work with it's own instance

I've added your questions to the FAQ section of the docs f28c6d2

**Comment by axefrog** [comment]
Excellent, thanks!
