### ISSUE TITLE
unclear how to specify calling convention for dll::import

### ISSUE THREAD

**Issue by SSE4** [apolukhin/Boost.DLL#14]
Hello,

I've just started using Boost.DLL in order to simplify loading of various WinApi functions exclusive to specific Windows versions, however, I've faced the issue (or may be it's just misunderstanding from my side).

it's pretty well-known there are multiple calling conventions around - cdecl, stdcall, fastcall, etc. most of WinApi functions are in stdcall calling convention, while default one for MSVC 2015 is cdecl (unless compiler options are changed).

I've read documentation on http://apolukhin.github.io/Boost.DLL/, as well as I've scanned source code a bit, but didn't find any avidence on how to specify calling convention of function I am importing.

example from tutorial9 works just fine, as it uses timeGetTime function which has no arguments. however, if I modify example (see my code below copy-pasted from tutorial9) to import function with at least one argument or more (e.g. GetStdHandle) I receive the following debugger error:

Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.

this indicates that Boost.DLL incorrectly interpreted stdcall function as cdeacl function that caused stack corruption.

I've googled a bit about calling convention and boost, and found the following two definitions:
#define BOOST_BIND_ENABLE_STDCALL
#define BOOST_MEM_FN_ENABLE_STDCALL 

unfortunately adding them has no effect.
if I add explicit __stdcall into the function typedef, then program no longer compiles

```c++
#include <boost/dll/import.hpp> // for import
#include <iostream>
#include <windows.h>

namespace dll = boost::dll;

int main()
{
	typedef HANDLE(GetStdHandle_fn)(DWORD nStdHandle);       // function signature
	boost::function<GetStdHandle_fn> plugin
		= dll::import<GetStdHandle_fn>(              // we import using C name, not alias! Using `import<>`
			"Kernel32.dll",                            // Windows dll
			"GetStdHandle"                           // function name
			);

	std::cout << "timeGetTime() returned " << plugin(STD_OUTPUT_HANDLE) << std::endl;
	return 0;
}
```

**Comment by apolukhin** [comment]
You're absolutely right. This seems to be a big problem of the C++ Standard and attempts to fix it lead to a world of dragons and undefined behavior:

* C++ Standard does not deal with calling conventions. Here's a quote from [dcl.link]:

Note: Some of the properties associated with an entity with language linkage are specific
to each implementation and are not described here. For example, a particular language linkage may be
associated with a particular form of representing names of objects and functions with external linkage, or
with a particular calling convention, etc. — end note

* MSVC++ treats calling conventions as a part of a type signature, making the `boost::function<void __fastcall()>` differ from `boost::function<void()>`.
* GCC does not treat calling conventions as a part of a function signature and looses them on any occurrence.

This makes it hard to find a good and portable solution. I'm still experimenting and trying to find a nice solution.

Until then a workaround like the following could be used:
```
#include <boost/dll/shared_library.hpp>
#include <iostream>
#include <windows.h>

namespace dll = boost::dll;

int main()
{
    typedef HANDLE(__stdcall GetStdHandle_fn)(DWORD nStdHandle);       // function signature

    dll::shared_library lib("Kernel32.dll");
    GetStdHandle_fn* f = &lib.get<GetStdHandle_fn>("GetStdHandle");
    auto plugin = [lib, f](DWORD nStdHandle) {
        return (*f)(nStdHandle);
    };

    std::cout << "GetStdHandle(STD_OUTPUT_HANDLE) returned " << plugin(STD_OUTPUT_HANDLE) << std::endl;
    return 0;
}
```

**Comment by apolukhin** [comment]
Applied some fixes, now importing with calling convention is more adequate. [Updated the examples](http://apolukhin.github.io/Boost.DLL/boost_dll/tutorial.html#boost_dll.tutorial.importing_a_c_function_from_windows_dll)
