### ISSUE TITLE
undefined behavior with import_alias<T> returning boost::function<T>

### ISSUE THREAD

**Issue by venediktov** [apolukhin/Boost.DLL#15]
in Import.hpp :
* \code 
* boost::function<int(int)> f = import<int(int)>("test_lib.so", "integer_func_name"); 
* \endcode 

template <class T> 
BOOST_DLL_IMPORT_RESULT_TYPE import(const boost::shared_ptr<shared_library>& lib, const char* name) { 
typedef typename boost::dll::detail::import_type<T>::base_type type; 
return type(lib, &lib->get<T>(name));  // returns refc_function<T>(lib , &lib->get<T>(name)) 
} 

It does not return aliasing shared_ptr constructor but rather your own refc_function
But I don't see how you maintain ref count after your conversion operator 
operator T*() const BOOST_NOEXCEPT ;  
is called assigning  to boost::function<T>

Basically this is how it looks after type substitution 

boost::function<int (int)> f = refc_function<int (int)>(lib, &lib->get<int(int)>(name)).operator T*() ;

What guarantees that the function pointer from shared_library ( aka return of dlsym ) is still valid after shared_library destructor ( see ~shared_library_impl() ) is called and actual shared lib is unloaded from the process ?
Can we continue to  hold the pointer returned by  dlsym() ?
Am I missing something ?

You handle it correctly in case of 
shared_ptr<T>  p = import<T>(lib, name) ; // this will share p and lib ref count 

But it does not look like it applies to another case.

Thanks,
Vlad.

**Comment by apolukhin** [comment]
> Basically this is how it looks after type substitution 
> boost::function f = refc_function(lib, &lib->get(name)).operator T*() ;

Actually it does not look like this. The whole `refc_function(lib, &lib->get(name))` is hold inside `boost::function`, and when you call `boost::function::operator()` then `refc_function::operator T*()` is evaluated and resulting function pointer is called (still keeping the instance of `refc_function` with a reference to so/dll inside `boost::function`). Here's some small example that prints out what is happenning:

```
#include <iostream>
#include <functional>

void foo() {
    std::cerr << "foo()\n";
}

struct refc_function {
    typedef void(foo_t)();
    foo_t* f_;
    
    refc_function(foo_t* f) : f_(f) {
        std::cerr << "refc_function(foo_t* f)\n"; 
    }
    
    ~refc_function() {
        std::cerr << "~refc_function()\n";
    }
    
    refc_function(const refc_function& h) : f_(h.f_) {
        std::cerr << "refc_function(const refc_function&)\n";
    }
    
    operator foo_t*() const {
        std::cerr << "operator foo_t*()\n";
        return f_;
    }
};
 
std::function<void()> factory() {
    return refc_function(&foo);
}

int main() {
    std::function<void()> f = factory();
    f();
}
```

That code will output:

```
refc_function(foo_t* f)
refc_function(const refc_function&)
~refc_function()
operator foo_t*()
foo()
~refc_function()
```

In steps:
```
std::function<void()> factory() {
    // 1: Constructing `refc_function(foo_t* f)` (let's call that unnamed instance `tmp`)
    return refc_function(&foo);
    // 2: Constructing `std::function`
    //  2.1: Copy constructing from `tmp` an instance of `refc_function` inside `std::function`
    //  2.2: Multiple internal `std::function` initializations
    // 3: Destructor of `tmp` is called (`~refc_function()`)
}

...

    // 0: calling `factory()`
    std::function<void()> f = factory();
    // 4: Calling `boost::function::operator()`
    //  4.1 `operator foo_t*()` for an instance of `refc_function` inside `std::function`
    //  4.2 actuall call by pointer, returned on step 4.1
    f();
    // 5: Destructing `std::function`
    //  5.1: Multiple internal `std::function` deinitializations
    //  5.2: Calling destructor for an instance of `refc_function` kept inside `std::function` (`~refc_function()`)
```

**Comment by venediktov** [comment]
Hi Antony,
Agree , your refc_function<T> does not implicitly get converted to T* .
I got confused when thinking something like  \:
boost::function\<void()\> f = boost::function\<void()\>(factory()) ; // thinking that ctor of boost::function is like boost::function( void (*) () )

In reality it has constructor template , so it can either take pointer to function or a functor holding that pointer to function \:

namespace boost {
...
...
template\< R BOOST_FUNCTION_COMMA BOOST_FUNCTION_TEMPLATE_PARAMS \>
struct function {
template\<typename Functor> 
function(Functor f) // this is constructor template 
..
...
} ;
} //namespace boost

In your case  Functor is  refc_function\<T\> with T = void ()  // for example
So the conversion  to actual function pointer that your refc_function functor is holding via conversion operator happens when we call f() which calls boost::function::invoke here \:

BOOST_FUNCTION_RETURN((*f)(BOOST_FUNCTION_ARGS));

f  is   refc_function<T> * 

Well, thanks for getting back to me !

Regards,
Vlad.

**Comment by venediktov** [comment]
On the top of that ,  I totally forgot I normally use something like boost::function\<T\> f = boost::bind(&U::mem_func, _1) ;
and I should of known that boost:function has ctor template and does not only allow pointers to function
