### ISSUE TITLE
Suggestion: load from memory?

### ISSUE THREAD

**Issue by axefrog** [apolukhin/Boost.DLL#16]
There seems to be a built-in assumption that we only ever want to load directly from the file system, however there are instances where loading from memory is useful though. In my project I'm planning on packaging up my plugins with any associated assets so that they can be downloaded as a unit, placed in the plugins folder as a single package, and then referenced via the [PhysFS](https://icculus.org/physfs/) library. This means that the boost filesystem requirement ends up being a hindrance rather than a help. Not sure how difficult this would be of course; I imagine there may be technicalities I'm unaware of. Something to consider, anyway?

**Comment by apolukhin** [comment]
Actually you're not the first who asks for such functionality. So I must at least add a new topic into FAQ.

All existing OS avoid loading shared libraries directly from userspace memory, so you'll find no syscall for such case. Currently Boost.DLL provides no means for honest loading shared objects from memory. This requires reimplementing dynamic linker logic in userspace for all the platforms, which is a huge amount of work and very error-prone. However working patches are welcomed!

Workaround would be to write plugin into a temporary file in RAM and load plugin from it:
```
#include <boost/filesystem.hpp>
#include <boost/dll.hpp>
using namespace boost;

dll:shared_library load_from_memory(unsigned char* data, std::size_t size, const filesystem::path& tmp_plugin_path = filesystem::unique_path() / "libplugin.so") {
    const filesystem::path plugin_location = filesystem::temp_directory_path() / tmp_plugin_path;
    filesystem::create_directories(plugin_location.parent_path());
    filesystem::ofstream ofs(plugin_location, std::ios::out|std::ios::bin|std::ios::trunc);
    ofs.write(data, size);

    return dll::shared_library(plugin_location);
}
```

But there's no guarantee that `filesystem::temp_directory_path()` will actually write to RAM, that's very platform dependent.

**Comment by axefrog** [comment]
Sure, thanks for the response. Maybe it's better to simply make it so certain types of plugins need to be unpacked...
