### ISSUE TITLE
Memory leak in example code

### ISSUE THREAD

**Issue by rettichschnidi** [apolukhin/Boost.DLL#26]
To my understanding, the [usage of the aliasing constructor](https://github.com/boostorg/dll/blob/e7225a8022e47f4a9fc4741dbe465a2da99d4b3a/example/tutorial8/refcounting_api.hpp#L34) in example8 induces a memory leak as the `my_refcounting_api` pointer `plugin` does [not get freed](http://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr) by this kind of shared_ptr:

> 8) The aliasing constructor: constructs a shared_ptr which shares ownership information with r, but holds an unrelated and unmanaged pointer ptr. Even if this shared_ptr is the last of the group to go out of scope, it will call the destructor for the object originally managed by r. However, calling get() on this will always return a copy of ptr. It is the responsibility of the programmer to make sure that this ptr remains valid as long as this shared_ptr exists, such as in the typical use cases where ptr is a member of the object managed by r or is an alias (e.g., downcast) of r.get()

How about some auxiliary wrapper:

```C++
template <typename T> struct ResourceWrapper {
  boost::dll::shared_library m_Dll;
  std::unique_ptr<T> m_T;
  ResourceWrapper(boost::dll::shared_library &dllLib, std::unique_ptr<T> i)
      : m_Dll(dllLib), m_T(std::move(i)) {}
};
```

Then use it along those lines:

```C++
boost::dll::shared_library myLib("myLib.so");
auto myObject = std::make_unique<MyType>();
auto myWrapper = std::make_shared<ResourceWrapper<MyType>>(myLib, std::move(myObject));
auto myAliasedSharedPointer = std::shared_ptr<MyType>(myWrapper, myWrapper->m_T.get());
```

I am not sure if this really THE way to go. But according to my understanding, this at least does not leak memory.

**Comment by apolukhin** [comment]
Thanks a lot for the error report and analysis!

Fixed in 2a09a92, polished in 73e4445.
