### ISSUE TITLE
Possible wrong include in path_from_handle.hpp

### ISSUE THREAD

**Issue by atzavellas** [apolukhin/Boost.DLL#28]
I think the 4th include line in the boost/dll/detail/path_from_handle.hpp is incorrect. It should be:
 
```
#include <boost/detail/winapi/GetLastError.hpp>
```
instead of 
```
#include <boost/detail/winapi/get_last_error.hpp>
```
The get_last_error.hpp doesn't exist in boost_1_60_0..

**Comment by apolukhin** [comment]
> The get_last_error.hpp doesn't exist in boost_1_60_0..

Yes, it's a [new file that exist in master branch of boost](https://github.com/boostorg/winapi/blob/master/include/boost/detail/winapi/get_last_error.hpp)

So everything is OK, no error here.

**Comment by atzavellas** [comment]
Ah ok, sorry for this I didn't see the boost master branch :)
