### ISSUE TITLE
Boost.DLL support for Android & iOS ?

### ISSUE THREAD

**Issue by kameal** [apolukhin/Boost.DLL#34]
Do we have document about how to build and use library in Android and iOS ? Is it possible?

**Comment by apolukhin** [comment]
Yes, it is possible.

What error do you get?

**Comment by kameal** [comment]
Thank for your reply. 
Currently, i used Boost 1.6.0 for my project (with Boost Asio), it's work perfect! 
I have question for this issue:
1. Can iOS load dynamic library (.dylib) or shared object (.so) ? 
2. Can Android do the same with question (1) ?
3. Boost.DLL is header only so i just need to include header only for my project?
4. If (1) and (2) possible. Then how can i build dynamic library or shared object for Android and iOS? Please point me to do that or share some document, tutorial about that!
Sorry for i'm not good at English! 
Best,

**Comment by apolukhin** [comment]
> Can iOS load dynamic library (.dylib) or shared object (.so) ?
Yes, it can. Shared library must be build for that platform.

> Can Android do the same with question (1) ?
Yes, it can. Shared library must be build for that platform.

> If (1) and (2) possible. Then how can i build dynamic library or shared object for Android and iOS?

I'm not sure how to do it for iOS.

For Android you will need an NDK. It has a GCC compiler in it, so you just build a shared library with it.

**Comment by kameal** [comment]
> For Android you will need an NDK. It has a GCC compiler in it, so you just build a shared library with it.

Thanks, so that with Android we can update code logic at run-time (if we already have shared library) ?

> I'm not sure how to do it for iOS.

That is my issue. I'm game developer with cocos2d-x. 
Update code logic at run-time. For Window, MacOS, Linux, Android now and i know that can be possible! But iOS is limited. Ohhhhh!!!

I'll try to do it with iOS. :)

**Comment by apolukhin** [comment]
How's your progress? Any library issues with iOS?

**Comment by kameal** [comment]
Hello.
I couldn't find the way to build shared library for iOS.

**Comment by apolukhin** [comment]
Looks like you will need a iOS8+ and have to build a "dynamic framework" to have a shared library: https://www.raywenderlich.com/65964/create-a-framework-for-ios

**Comment by kameal** [comment]
Hi,
How nice! Thanks, i'll take a look at this tutorial!

**Comment by apolukhin** [comment]
Have you succeeded?

**Comment by kameal** [comment]
Sorry for late reply.
I'm on holiday. 
I'll try after February

**Comment by apolukhin** [comment]
Any news?

**Comment by apolukhin** [comment]
Looks like a fixed issue.

**Comment by kameal** [comment]
Sorry @apolukhin  for late reply.
I failed this project.  :((
My Team Leader resolved with new solution (use LUA script instead c++).
But, i wanna know how to fix issue. If you have free time, please make a tutorial for this.
Thanks,
