### ISSUE TITLE
missing example/shared_library_load_plugin.cpp

### ISSUE THREAD

**Issue by hia3** [apolukhin/Boost.DLL#45]
Referenced [here](https://github.com/apolukhin/Boost.DLL/blob/develop/example/Jamfile.v2#L35).

Also [example/tutorial3/load_self.cpp](https://github.com/apolukhin/Boost.DLL/blob/develop/example/Jamfile.v2#L43)

**Comment by apolukhin** [comment]
`example/Jamfile.v2` newer was used and was newer tested. It's an obsolete file, so I just removed it.

Many thanks for reminding about its existence.
