### ISSUE TITLE
smart_library.get_mem_fn failed to call with 64bit dll

### ISSUE THREAD

**Issue by c8jiang** [apolukhin/Boost.DLL#47]
Environment: Windows 10 1903; MSVC 14.2; Boost 1.70
A member function in my class was successfully imported only in x86 and failed in x64.

`auto f = sm.get_mem_fn<alias, void(Callback)>("set_callback");` give me an exception in x64.
![image](https://user-images.githubusercontent.com/12910635/63397858-6ed3e200-c3fe-11e9-806a-bae0999e467c.png)

My prject file: [test_class.zip](https://github.com/apolukhin/Boost.DLL/files/3523318/test_class.zip)

My class like this: 
`#include <iostream>`
`#include <functional>`
`#include <boost/config.hpp>`

`struct CallbackInfo`
`{`
        `void* p;`
	`int a;`
	`int b;`
	`void* pContext;`
`};`
`//using Callback = std::function<void(CallbackInfo* pInfo)>;`
`typedef void(__stdcall* Callback)(CallbackInfo* pInfo);`
`class BOOST_SYMBOL_EXPORT test_a`
`{`
	`int _a;`
`public:`
	`test_a();`
	`test_a(int a);`
	`~test_a();`
	`void print();`
	`bool large_than(int a);`
	`const char* number();`
	**void set_callback(Callback callback);**
	`static std::size_t size();`
	`std::string name() const;`
`};`

**Comment by apolukhin** [comment]
Many thanks for the report!

Unfortunately I've found no good way to support such cases. I've added a static assert to detect the problem at compile time, rather than at run time. PRs wit better solutions are welcome!
