### ISSUE TITLE
Can we add BOOST_DLL_USE_STD to specifiy if we want to use boost version or std version of library

### ISSUE THREAD

**Issue by LogicFan** [apolukhin/Boost.DLL#48]
My thought is we could have a BOOST_DLL_USE_STD macro to control if we want to use the boost version or std version of the following:
- shared_ptr
- filesystem
- type_traits

The way I am thinking is that we could define `boost::dll::shared_ptr` in config.hpp and use macro to control if we want to use the std version or the boost version, similar to how the `boost::dll::fs` is done.

Just want to ask is this an acceptable solution, I could do this if this idea is approved.

**Comment by apolukhin** [comment]
How about just putting that functionality into existing `BOOST_DLL_USE_STD_FS` macro? If C++17's std::filesystem::path is available, then all the C++11 stuff should be already available on the platform
