### ISSUE TITLE
use extern "C++" instead of extern "C" will crash

### ISSUE THREAD

**Issue by qicosmos** [apolukhin/Boost.DLL#50]
I want to export a std::string foo(), and use extern "C++" to avoid a warning, however when i get the function, it crashed.
So i want to know if boos.dll support extern "C++" or not?
How can i export such kind of c++ function with boost.dll?

**Comment by apolukhin** [comment]
`extern "C++"` is supported, but with it your function will be mangled and you have to provide a mangled name during import. Find the correct mangled name via inspecting the symbols of your binary via platform specific tools.

You could also use the [mangled import](https://www.boost.org/doc/libs/1_74_0/doc/html/boost_dll/mangled_import.html) but that feature is experimental and may crush on complex cases
