### ISSUE TITLE
Is Boost.DLL really not thread safe on macOS?

### ISSUE THREAD

**Issue by tmwnewbold** [apolukhin/Boost.DLL#53]
The documentation clearly states that Boost.DLL is not thread safe on macOS due to thread safety issues with dlopen(). Is this really still true or is this bit of documentation out of date? I'm unaware of any thread safety problems with dlopen on any recent version of macOS, and our system is both heavily threaded and a heavy user of dlopen. We make no special affordances for macOS vs Linux vs Windows. Or is Boost.DLL using some undocumented macOS APIs that do still have issues?

**Comment by apolukhin** [comment]
It's an issue in dlopen on MacOS, here's an example https://issues.apache.org/jira/browse/MESOS-164

If that issue was fixed in latest versions, please provide a link to official changelog and I'll adjust the Boost docs.
