### ISSUE TITLE
Choose another shared library for test

### ISSUE THREAD

**Issue by hdu-sdlzx** [apolukhin/Boost.DLL#61]
libdl is merge into libc in glibc-2.34[1], so test/shared_library_load_test.cpp(248) failes because libdl.so no longer exists.
Maybe we should choose another library for test?
[1]https://sourceware.org/glibc/wiki/Release/2.34

test log:
testing.capture-output ../../../bin.v2/libs/dll/test/shared_library_load_test.test/gcc-12/release/debug-symbols-on/pch-off/threading-multi/visibility-hidden/shared_library_load_test.run
====== BEGIN OUTPUT ======
Library: "../../../bin.v2/libs/dll/test/gcc-12/release/debug-symbols-on/pch-off/threading-multi/visibility-hidden/libtest_library.so.1.80.0"shared_library_load_test.cpp(248): test 'false' failed in function 'int main(int, char**)'
platform_independent_path: "../../../bin.v2/libs/dll/test/gcc-12/release/debug-symbols-on/pch-off/threading-multi/visibility-hidden/test_library"

Program location: "/home/sdlzx/rpmbuild/BUILD/boost_1_80_0/bin.v2/libs/dll/test/shared_library_load_test.test/gcc-12/release/debug-symbols-on/pch-off/threading-multi/visibility-hidden/shared_library_load_test"
Library location: "/home/sdlzx/rpmbuild/BUILD/boost_1_80_0/bin.v2/libs/dll/test/shared_library_load_test.test/gcc-12/release/debug-symbols-on/pch-off/threading-multi/visibility-hidden/shared_library_load_test"1 error detected.

EXIT STATUS: 1
====== END OUTPUT ======

**Comment by hdu-sdlzx** [comment]
ping @apolukhin

**Comment by hdu-sdlzx** [comment]
ping @apolukhin @pdimov

**Comment by apolukhin** [comment]
I'm fine with some other library. Any suggestions?
