### ISSUE TITLE
Docs: compilers supported

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [apolukhin/Boost.DLL#7]
Please note in the docs which compilers and compiler versions are supported

**Comment by apolukhin** [comment]
There's a note about supported compilers in README.md :  "Library was tested on Windows (MinGW and MSVC compilers) and Linux(GCC and CLANG compilers). MacOS is upcoming."

Library is meant to be **usable on all the modern C++98 compilers and platforms**, but while it is not accepted into Boost I have no access to some of the of the compilers and platforms.

If library fails on your compiler - please report an error and I'll gladly fix it.

**Comment by Bulat-Ziganshin** [comment]
my situation: i write program that is already somewhat portable i.e. it compiles with msvc2013 and gcc48 on win/linux. and i hope to compile it with other OS/compilers in the furture. i consider using various libraries and one reason behind my decisions is portability of these libraries, i.e. how  many OS/compiler/version combinations they are support. checking every library i can potentially use with all these compilers are impractical, of course. so if you can maintain list of compilers that checked and work as well as ones that doesn't work, it may help people like me

**Comment by Bulat-Ziganshin** [comment]
are you know about Travis CI free online service? it may be that you need, i regularly see it used in various github projects, f.e.: https://github.com/BoostGSoC13/boost.afio (scroll down page - this table is populated by the Travis site)

read here: https://travis-ci.com/

**Comment by Bulat-Ziganshin** [comment]
you are right. i just overlooked еры note in README. for my purposes, support for latest compiler versions is enough. may be it should be written in bold for dummies like me, or you can produce cute table like here: https://github.com/BoostGSoC13/boost.afio/blob/master/Readme.md

**Comment by apolukhin** [comment]
Project is already using TravisCI. Unfortunately TravisCI is bound to Linux, so I can test only GCC and Clang compilers in different modes. MSVC is also tested thanks to some of my followers!

I've already written to the TravisCI admins and requested a MacOS guest OS. They replied to me that they have too many requests and will give me a note when they'll have enough power to run more MacOS guests.

MinGW has an [issue with weak exports](https://sourceware.org/bugzilla/show_bug.cgi?id=17480), but the workaround is trivial and described in docs. All the tests pass with this workaround.

According to my experience Intel C++ and VaCPP are pretty close to GCC, so there must be no issues (or at least they'll be easy to fix). Borland C++ is not a compiler that is supported by Boost, but the latest versions of Borland x64 are using Clang as a backend => no issues must be there.

AndroidOS is widely used at my work, so in a few months I'll make sure that everything is OK on Android.

**Comment by apolukhin** [comment]
Boost.DLL is accepted into the Boost. Now all the major compilers and platforms must be supported + MacOS fixes were applied during library review, so now it is known to work on MacOS.
