### ISSUE TITLE
can not invoke the __stdcall function exported by windows dll!

### ISSUE THREAD

**Issue by cxq2003** [apolukhin/Boost.DLL#8]
compile ok, run error!
boost 1.57 and visual studio 2010 sp1 on windows 7 64bit!

**Comment by apolukhin** [comment]
Could you please provide source code to reproduce the error?

**Comment by apolukhin** [comment]
Added an example to [tutorial](http://apolukhin.github.io/Boost.DLL/boost_dll/tutorial.html#boost_dll.tutorial.importing_a_c_function_from_windows_dll). Everything works well in tests.

Please provide code to reproduce your error.
